### ISSUE TITLE
[feat] alterações no script de `create_yaml_file.py`

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados-dev#365]
- [x] incorporar script de construção do .sql no `create_yaml_file`
- [x] incorporar tests  no `create_yaml_file`
   - [x] conexão com diretórios
   - [x] colunas nao inteiramente nulas
   - [x] teste de chave únicas
- [x] incluir config com alias ao criar o .sql e ajustar o nome do arquivo para que fique `dataset__table.sql`

**Comment by arthurfg** [comment]
- [x] incluir possiblidade da coluna do diretório não ter bucket
- [ ] levantar erro caso o preenchimento na coluna de diretório não permitir montar o yaml
- [ ] mudar o teste de chave unica para combinação de colunas ao inves de ter só uma coluna
- [ ] incluir coluna de chave unica na arquitetura
- [ ] aplicar not_null_proportion para todas as colunas
