### ISSUE TITLE
[dados] censo 2022

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados-dev#388]

**Comment by arthurfg** [comment]
Tabelas no storage:

- [ ] [area_territorial_densidade_demografica_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/area_territorial_densidade_demografica_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [domicilios_moradores_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/domicilios_moradores_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [domicilios_moradores_terras_indigenas/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/domicilios_moradores_terras_indigenas?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [domicilios_moradores_territorios_quilombolas/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/domicilios_moradores_territorios_quilombolas?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [domicilios_pelo_menos_um_territorios_quilombolas/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/domicilios_pelo_menos_um_territorios_quilombolas?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [domicilios_recenseados_especie_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/domicilios_recenseados_especie_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [indice_envelhecimento_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/indice_envelhecimento_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [indigenas_domicilios_moradores_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/indigenas_domicilios_moradores_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [indigenas_domicilios_pelo_menos_um_morador_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/indigenas_domicilios_pelo_menos_um_morador_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [indigenas_populacao_residente_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/indigenas_populacao_residente_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [populacao_grupos_idade_uf/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/populacao_grupos_idade_uf?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [populacao_residente_territorios_quilombolas/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/populacao_residente_territorios_quilombolas?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [quilombolas_domicilios_moradores_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/quilombolas_domicilios_moradores_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
- [ ] [quilombolas_domicilios_pelo_menos_um_morador_municipio/](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_ibge_censo_2022/quilombolas_domicilios_pelo_menos_um_morador_municipio?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=basedosdados-dev)
